"""Inventário da edição de 1904. pdf = página 1-indexed do PDF colorido."""

from __future__ import annotations

# crop: fração (x0, y0, x1, y1) da gravura de cabeçalho na primeira página.
# None = peça sem gravura de abertura.

DEFAULT_CROP = (0.06, 0.015, 0.96, 0.40)

PIECES: list[dict] = [
    {
        "id": "a-quem-ler",
        "title": "A quem ler",
        "printed": 5,
        "pdf": [7, 8],
        "crop": None,
        "kind": "preface",
    },
    {
        "id": "a-avo",
        "title": "A Avó",
        "printed": 7,
        "pdf": [9, 10, 11],
        "crop": (0.07, 0.02, 0.95, 0.395),
        "kind": "poem",
    },
    {
        "id": "o-passaro-captivo",
        "title": "O Passaro captivo",
        "printed": 10,
        "pdf": [12, 13, 14],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "o-sol",
        "title": "O Sol",
        "printed": 13,
        "pdf": [15, 16],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "as-estrellas",
        "title": "As Estrellas",
        "printed": 15,
        "pdf": [17, 18],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "a-borboleta",
        "title": "A Borboleta",
        "printed": 17,
        "pdf": [19, 20, 21],
        "crop": (0.04, 0.01, 0.97, 0.48),
        "kind": "poem",
    },
    {
        "id": "natal",
        "title": "Natal",
        "printed": 20,
        "pdf": [22, 23],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "os-reis-magos",
        "title": "Os Reis Magos",
        "printed": 22,
        "pdf": [24, 25, 26],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "os-pobres",
        "title": "Os Pobres",
        "printed": 25,
        "pdf": [27, 28],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "a-boneca",
        "title": "A boneca",
        "printed": 27,
        "pdf": [29, 30],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "as-estacoes",
        "title": "As Estações",
        "printed": 29,
        "pdf": list(range(31, 41)),
        "crop": (0.0, 0.0, 1.0, 1.0),
        "kind": "poem",
    },
    {
        "id": "as-formigas",
        "title": "As formigas",
        "printed": 39,
        "pdf": [41, 42, 43],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "o-universo",
        "title": "O universo",
        "printed": 42,
        "pdf": [44, 45, 46],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "domingo",
        "title": "Domingo",
        "printed": 45,
        "pdf": [47, 48],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "plutao",
        "title": "Plutão",
        "printed": 47,
        "pdf": [49, 50, 51],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "o-boi",
        "title": "O Boi",
        "printed": 50,
        "pdf": [52, 53],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "o-avo",
        "title": "O Avô",
        "printed": 52,
        "pdf": [54, 55],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "deus",
        "title": "Deus",
        "printed": 54,
        "pdf": [56],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "o-remedio",
        "title": "O Remedio",
        "printed": 55,
        "pdf": [57, 58, 59, 60],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "justica",
        "title": "Justiça",
        "printed": 59,
        "pdf": [61, 62],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "o-tempo",
        "title": "O tempo",
        "printed": 61,
        "pdf": [63, 64],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "a-madrugada",
        "title": "A madrugada",
        "printed": 63,
        "pdf": [65, 66],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "meio-dia",
        "title": "Meio-dia",
        "printed": 65,
        "pdf": [67, 68],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "ave-maria",
        "title": "Ave-Maria",
        "printed": 67,
        "pdf": [69, 70],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "meia-noite",
        "title": "Meia noite",
        "printed": 69,
        "pdf": [71, 72],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "os-mezes",
        "title": "Os mezes",
        "printed": 71,
        "pdf": list(range(73, 99)),
        "crop": (0.0, 0.0, 1.0, 1.0),
        "kind": "poem",
    },
    {
        "id": "anno-bom",
        "title": "Anno Bom",
        "printed": 97,
        "pdf": [99, 100, 101],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "as-flores",
        "title": "As flores",
        "printed": 100,
        "pdf": [102, 103],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "a-infancia",
        "title": "A Infancia",
        "printed": 102,
        "pdf": [104, 105],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "a-mocidade",
        "title": "A mocidade",
        "printed": 104,
        "pdf": [106],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "a-velhice",
        "title": "A Velhice",
        "printed": 105,
        "pdf": [107, 108],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "o-trabalho",
        "title": "O trabalho",
        "printed": 107,
        "pdf": [109, 110],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "a-coragem",
        "title": "A Coragem",
        "printed": 109,
        "pdf": [111, 112],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "a-modestia",
        "title": "A Modestia",
        "printed": 111,
        "pdf": [113],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "credo",
        "title": "Crédo",
        "printed": 112,
        "pdf": [114, 115],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "a-patria",
        "title": "A Patria",
        "printed": 114,
        "pdf": [116, 117],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "a-caza",
        "title": "A Caza",
        "printed": 116,
        "pdf": [118, 119],
        "crop": DEFAULT_CROP,
        "kind": "poem",
    },
    {
        "id": "fabulas",
        "title": "Fabulas",
        "printed": 118,
        "pdf": list(range(120, 130)),
        "crop": DEFAULT_CROP,
        "kind": "fable",
    },
]


def by_id(pid: str) -> dict:
    for p in PIECES:
        if p["id"] == pid:
            return p
    raise KeyError(pid)
